In [1]:
# Highly Efficient
# Cross-platform
# Deep integration with the keras library

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [3]:
import tensorflow as tf


In [4]:
tf.executing_eagerly()

True

In [5]:
a = tf.Variable(20)

In [8]:
type(a)  # tensor is array -> Tensorflow -> Flow of calculations wrt arrays
# It allows us to Do many large number of calculations wrt numpy
# GPU increases the speed of parallel processing

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [9]:
a.assign(30)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=30>

In [10]:
# tensorboard is a visual tool for tensorflow
from datetime import datetime
import os
import pathlib

t = datetime.utcnow().strftime("%Y%m%d%H%M%S")
log_dir = "tf_logs"
logd = "{}/r{}/".format(log_dir, t)

from pathlib import Path
home = str(Path.home())

logdir = os.path.join(os.sep, home , logd)

if not os.path.exists(logdir):
  os.makedirs(logdir)

In [11]:
logdir

'/root/tf_logs/r20211025184357/'

# Tensorflow Tensors


In [12]:
a = tf.constant(10)
b = tf.constant(30)

In [13]:
a.numpy()

10

In [14]:
a*b


<tf.Tensor: shape=(), dtype=int32, numpy=300>

In [15]:
tf.multiply(a,b).numpy()

300

In [16]:
a_mat = tf.constant([[1,2],[3,4]])
b_mat = tf.constant([[5,6],[7,8]])


In [17]:
tf.matmul(a_mat, b_mat)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [18]:
a.assign(8)

AttributeError: ignored

In [19]:
print(a_mat)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [20]:
print(b_mat)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


# tf.Variable


In [21]:
var = tf.Variable(3.3)
var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.3>

In [22]:
a_var = tf.Variable(np.random.randint(1, 100, (4, 5)))

In [23]:
a_var

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int64, numpy=
array([[88, 27,  1, 36, 84],
       [28, 84, 40, 59, 27],
       [37, 92, 89, 61, 28],
       [87, 54, 87, 16, 72]])>

In [24]:
var.assign(40)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=40.0>

In [25]:
print("Original: ", var.numpy())
print("Add 1:", var.assign_add(1.).numpy())
print("Sub 5:", var.assign_sub(5.).numpy())

Original:  40.0
Add 1: 41.0
Sub 5: 36.0


In [26]:
v = tf.Variable([[3., 3.2], [1.2, 2.2]])

In [27]:
print(v.name)
print(v.dtype)
print(v.shape)
print(v.device)

Variable:0
<dtype: 'float32'>
(2, 2)
/job:localhost/replica:0/task:0/device:CPU:0


In [28]:
# create Computational graph with @tf.function
@tf.function
def func(a,b):
  z = tf.multiply(a,b, name='z')
  y1 = tf.constant(3, name='3')
  y2 = tf.constant(4)
  w1 = tf.add(z, y1, name='w1')
  w2 = tf.add(z, y2, name='w2')

  return(w1+w2)

In [30]:
# ability to compute parallely
func(10, 20)

<tf.Tensor: shape=(), dtype=int32, numpy=407>

In [31]:
writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on()

In [32]:
a = tf.constant(3)
b = tf.constant(4)

func(a, b)
with writer.as_default():
  tf.summary.trace_export(
      name = "func", 
      step = 0, 
      profiler_outdir=logdir
  )

In [33]:
logdir

'/root/tf_logs/r20211025184357/'

In [38]:
!tensorboard --logdir $logdir

2021-10-25 19:18:29.725157: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-10-25 19:18:29.725230: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d0e117ba7533): /proc/driver/nvidia/version does not exist

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.6.0 at http://localhost:6006/ (Press CTRL+C to quit)
^C


In [42]:
# tensorboard just represents the graph(DAG) made by tf.function
w = tf.Variable(5.0)
with tf.GradientTape() as tape:
  # Gradient -> How much of one thing will change wrt some other thing
  expression = tf.exp(w) + 2*w + w*w

grad = tape.gradient(expression, w)
print(f'the gradient of exp at {w.numpy()} is {grad.numpy()}')


the gradient of exp at 5.0 is 160.4131622314453


In [41]:
def sigmoid(x):
  return 1/(1 + tf.exp(-x))

In [46]:
x = tf.Variable(0.)
with tf.GradientTape() as tape:
  sig = sigmoid(x)

res = tape.gradient(sig, x).numpy()
print(f'the gradient of sigmoid function at {x.numpy()} is {res}')

the gradient of sigmoid function at 0.0 is 0.25
